export const wmoCodeInterpretation: Record<number, string> = {
	0: "Clear sky",
	1: "Mainly clear",
	2: "Partly cloudy",
	3: "Overcast",
	45: "Foggy",
	48: "Depositing rime fog",
	51: "Light drizzle",
	53: "Moderate drizzle",
	55: "Dense drizzle",
	56: "Light freezing drizzle",
	57: "Dense freezing drizzle",
	61: "Slight rain",
	63: "Moderate rain",
	65: "Heavy rain",
	66: "Light freezing rain",
	67: "Heavy freezing rain",
	71: "Slight snow fall",
	73: "Moderate snow fall",
	75: "Heavy snow fall",
	77: "Snow grains",
	80: "Slight rain showers",
	81: "Moderate rain showers",
	82: "Violent rain showers",
	85: "Slight snow showers",
	86: "Heavy snow showers",
	95: "Thunderstorm (slight or moderate)",
	96: "Thunderstorm with slight hail",
	99: "Thunderstorm with heavy hail",
};

export const wmoToIcon: Record<number, string> = {
	0: "day-sunny",
	1: "day-sunny-overcast",
	2: "day-cloudy",
	3: "cloudy",
	45: "fog",
	48: "fog",
	51: "sprinkle",
	53: "showers",
	55: "rain",
	56: "rain-mix",
	57: "rain-mix",
	61: "rain",
	63: "rain",
	65: "rain",
	66: "rain-mix",
	67: "rain-mix",
	71: "snow",
	73: "snow",
	75: "snow",
	77: "snow",
	80: "showers",
	81: "showers",
	82: "rain",
	85: "snow",
	86: "snow",
	95: "thunderstorm",
	96: "thunderstorm",
	99: "hail",
};

export function getWeatherDescription(code: number): string {
	return wmoCodeInterpretation[code] || "Unknown weather condition";
}
